/**
 * Historical awards snapshot (kind 34011).
 *
 * This is the half of the graph that turns a listings site into a knowledge
 * base. Opportunities describe the future; awards describe the past; funders
 * join them. Together they answer questions no single platform answers today,
 * e.g. "which funders have actually paid for open source privacy work in
 * Europe, and do any of them have an open call right now?"
 *
 * Amounts and pairings below are illustrative of the shape produced by the
 * IRS-990 and funder-report adapters, not a verified financial record.
 */
export interface SeedAward {
  sourceId: string;
  funder: { name: string; id: string };
  recipient: string;
  purpose: string;
  amount: { value: number; currency: string };
  year: string;
  topics: string[];
  countries: string[];
  projectUrl?: string;
  source: 'irs-990' | 'funder-report' | 'press-release' | 'community';
}

export const SEED_AWARDS: SeedAward[] = [
  // --- Open source / privacy in Europe -------------------------------------
  {
    sourceId: 'nlnet',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    recipient: 'Tor Project — Onion Services Hardening',
    purpose: 'Improve onion service reliability and reduce metadata leakage in the v3 rendezvous protocol.',
    amount: { value: 50000, currency: 'EUR' },
    year: '2024',
    topics: ['privacy', 'open source', 'security', 'internet'],
    countries: ['GLOBAL'],
    projectUrl: 'https://www.torproject.org/',
    source: 'funder-report',
  },
  {
    sourceId: 'nlnet',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    recipient: 'Delta Chat',
    purpose: 'End-to-end encrypted messaging over standard email infrastructure, with WebXDC app support.',
    amount: { value: 47000, currency: 'EUR' },
    year: '2024',
    topics: ['privacy', 'open source', 'messaging'],
    countries: ['DE'],
    projectUrl: 'https://delta.chat/',
    source: 'funder-report',
  },
  {
    sourceId: 'nlnet',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    recipient: 'Sequoia PGP',
    purpose: 'A modern, safe OpenPGP implementation in Rust with usable key management.',
    amount: { value: 50000, currency: 'EUR' },
    year: '2023',
    topics: ['privacy', 'cryptography', 'open source', 'security'],
    countries: ['DE'],
    projectUrl: 'https://sequoia-pgp.org/',
    source: 'funder-report',
  },
  {
    sourceId: 'nlnet',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    recipient: 'Peertube — Federated Video Hosting',
    purpose: 'Improve moderation tooling and live streaming resilience across the federated instance network.',
    amount: { value: 42000, currency: 'EUR' },
    year: '2023',
    topics: ['open source', 'decentralization', 'internet'],
    countries: ['FR'],
    projectUrl: 'https://joinpeertube.org/',
    source: 'funder-report',
  },
  {
    sourceId: 'nlnet',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    recipient: 'Nym Mixnet Research',
    purpose: 'Formal analysis of mixnet anonymity guarantees under partial adversarial relay control.',
    amount: { value: 38000, currency: 'EUR' },
    year: '2022',
    topics: ['privacy', 'cryptography', 'research'],
    countries: ['CH'],
    source: 'funder-report',
  },
  {
    sourceId: 'prototype-fund',
    funder: { name: 'Prototype Fund', id: 'prototype-fund' },
    recipient: 'OpenSCHUFA / AlgorithmWatch',
    purpose: 'Reverse-engineer and audit German credit scoring algorithms using crowdsourced data.',
    amount: { value: 47500, currency: 'EUR' },
    year: '2023',
    topics: ['privacy', 'accountability', 'civic tech', 'open source'],
    countries: ['DE'],
    source: 'funder-report',
  },
  {
    sourceId: 'prototype-fund',
    funder: { name: 'Prototype Fund', id: 'prototype-fund' },
    recipient: 'Kartenkiste — Open Municipal Data Maps',
    purpose: 'Self-hostable mapping tool for German municipalities publishing open geodata.',
    amount: { value: 47500, currency: 'EUR' },
    year: '2024',
    topics: ['civic tech', 'open data', 'open source'],
    countries: ['DE'],
    source: 'funder-report',
  },
  {
    sourceId: 'sovereign-tech',
    funder: { name: 'Sovereign Tech Agency', id: 'sovereign-tech-agency' },
    recipient: 'OpenSSH',
    purpose: 'Security review, code modernisation and long-term maintenance capacity for OpenSSH.',
    amount: { value: 200000, currency: 'EUR' },
    year: '2024',
    topics: ['security', 'open source', 'infrastructure', 'maintenance'],
    countries: ['GLOBAL'],
    projectUrl: 'https://www.openssh.com/',
    source: 'funder-report',
  },
  {
    sourceId: 'sovereign-tech',
    funder: { name: 'Sovereign Tech Agency', id: 'sovereign-tech-agency' },
    recipient: 'GNU Coreutils / Bash maintenance',
    purpose: 'Fund maintainer time for foundational GNU userland tooling.',
    amount: { value: 130000, currency: 'EUR' },
    year: '2024',
    topics: ['open source', 'infrastructure', 'maintenance'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'sovereign-tech',
    funder: { name: 'Sovereign Tech Agency', id: 'sovereign-tech-agency' },
    recipient: 'Fortran Package Manager & LFortran',
    purpose: 'Modernise scientific Fortran tooling underpinning climate and physics codebases.',
    amount: { value: 95000, currency: 'EUR' },
    year: '2023',
    topics: ['open source', 'science', 'infrastructure', 'climate'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'sovereign-tech',
    funder: { name: 'Sovereign Tech Agency', id: 'sovereign-tech-agency' },
    recipient: 'curl',
    purpose: 'Security hardening, fuzzing infrastructure and documentation for curl and libcurl.',
    amount: { value: 180000, currency: 'EUR' },
    year: '2023',
    topics: ['security', 'open source', 'infrastructure', 'maintenance'],
    countries: ['SE'],
    projectUrl: 'https://curl.se/',
    source: 'funder-report',
  },

  // --- AI safety -----------------------------------------------------------
  {
    sourceId: 'open-philanthropy',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    recipient: 'Redwood Research',
    purpose: 'Empirical research on adversarial training and AI control protocols.',
    amount: { value: 6500000, currency: 'USD' },
    year: '2024',
    topics: ['ai safety', 'ai', 'research'],
    countries: ['US'],
    source: 'funder-report',
  },
  {
    sourceId: 'open-philanthropy',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    recipient: 'MIT Algorithmic Alignment Group',
    purpose: 'Mechanistic interpretability research and student support.',
    amount: { value: 1900000, currency: 'USD' },
    year: '2024',
    topics: ['ai safety', 'ai', 'research', 'machine learning'],
    countries: ['US'],
    source: 'funder-report',
  },
  {
    sourceId: 'open-philanthropy',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    recipient: 'Apollo Research',
    purpose: 'Evaluations for deceptive alignment and scheming behaviour in frontier models.',
    amount: { value: 1400000, currency: 'USD' },
    year: '2023',
    topics: ['ai safety', 'ai', 'research'],
    countries: ['GB'],
    source: 'funder-report',
  },
  {
    sourceId: 'open-philanthropy',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    recipient: 'Johns Hopkins Center for Health Security',
    purpose: 'Pandemic preparedness policy research and biosecurity field-building.',
    amount: { value: 4300000, currency: 'USD' },
    year: '2023',
    topics: ['biosecurity', 'global health', 'policy', 'research'],
    countries: ['US'],
    source: 'funder-report',
  },
  {
    sourceId: 'aisafety-funding',
    funder: { name: 'Manifund', id: 'manifund' },
    recipient: 'Independent interpretability researcher cohort',
    purpose: 'Six months of independent research funding for four early-career interpretability researchers.',
    amount: { value: 145000, currency: 'USD' },
    year: '2024',
    topics: ['ai safety', 'research', 'ai'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },

  // --- Bitcoin / Nostr -----------------------------------------------------
  {
    sourceId: 'opensats',
    funder: { name: 'OpenSats', id: 'opensats' },
    recipient: 'Bitcoin Core contributor grants (cohort)',
    purpose: 'Long-term funding for multiple Bitcoin Core contributors working on review, testing and P2P.',
    amount: { value: 1200000, currency: 'USD' },
    year: '2024',
    topics: ['bitcoin', 'open source', 'security'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'opensats',
    funder: { name: 'OpenSats', id: 'opensats' },
    recipient: 'Nostr relay and client ecosystem grants',
    purpose: 'Funding for relay implementations, client development and NIP authorship across the Nostr ecosystem.',
    amount: { value: 680000, currency: 'USD' },
    year: '2024',
    topics: ['nostr', 'open source', 'decentralization', 'privacy'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'opensats',
    funder: { name: 'OpenSats', id: 'opensats' },
    recipient: 'Payjoin Dev Kit',
    purpose: 'Reference implementation of BIP-78 payjoin to improve on-chain transaction privacy.',
    amount: { value: 95000, currency: 'USD' },
    year: '2023',
    topics: ['bitcoin', 'privacy', 'open source'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'nostr-announcements',
    funder: { name: 'Human Rights Foundation', id: 'human-rights-foundation' },
    recipient: 'Bitcoin education in Sub-Saharan Africa',
    purpose: 'Grassroots developer training and translation of Bitcoin and Nostr documentation.',
    amount: { value: 45000, currency: 'USD' },
    year: '2024',
    topics: ['bitcoin', 'education', 'human rights'],
    countries: ['NG', 'KE', 'GH'],
    source: 'press-release',
  },
  {
    sourceId: 'nostr-announcements',
    funder: { name: 'Human Rights Foundation', id: 'human-rights-foundation' },
    recipient: 'Censorship-resistant publishing tooling',
    purpose: 'Nostr-based publishing stack for journalists operating under state censorship.',
    amount: { value: 60000, currency: 'USD' },
    year: '2024',
    topics: ['human rights', 'journalism', 'nostr', 'censorship resistance'],
    countries: ['GLOBAL'],
    source: 'press-release',
  },

  // --- US philanthropy via IRS 990 ----------------------------------------
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'Ford Foundation', id: 'ford-foundation' },
    recipient: 'Open Collective Foundation — critical digital infrastructure',
    purpose: 'Fiscal hosting and maintainer support for widely-used open source dependencies.',
    amount: { value: 1000000, currency: 'USD' },
    year: '2023',
    topics: ['open source', 'infrastructure', 'public goods'],
    countries: ['US'],
    source: 'irs-990',
  },
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'Ford Foundation', id: 'ford-foundation' },
    recipient: 'Digital Infrastructure Insights Fund',
    purpose: 'Collaborative research fund studying how critical digital infrastructure is sustained.',
    amount: { value: 750000, currency: 'USD' },
    year: '2023',
    topics: ['open source', 'research', 'infrastructure', 'policy'],
    countries: ['US'],
    source: 'irs-990',
  },
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'Mozilla Foundation', id: 'mozilla-foundation' },
    recipient: 'Common Voice — multilingual speech datasets',
    purpose: 'Community-collected open speech data for under-resourced languages.',
    amount: { value: 400000, currency: 'USD' },
    year: '2023',
    topics: ['ai', 'open data', 'accessibility', 'open source'],
    countries: ['GLOBAL'],
    source: 'irs-990',
  },
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'John S. and James L. Knight Foundation', id: 'knight-foundation' },
    recipient: 'Institute for Nonprofit News',
    purpose: 'Shared technology and back-office infrastructure for member newsrooms.',
    amount: { value: 2000000, currency: 'USD' },
    year: '2023',
    topics: ['journalism', 'infrastructure', 'civic tech'],
    countries: ['US'],
    source: 'irs-990',
  },
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'John S. and James L. Knight Foundation', id: 'knight-foundation' },
    recipient: 'Documenting COVID-19 / MuckRock',
    purpose: 'Public records infrastructure and open source FOIA tooling for local newsrooms.',
    amount: { value: 500000, currency: 'USD' },
    year: '2022',
    topics: ['journalism', 'open data', 'open source', 'accountability'],
    countries: ['US'],
    source: 'irs-990',
  },
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'Arcadia Fund', id: 'arcadia-fund' },
    recipient: 'Internet Archive — open library infrastructure',
    purpose: 'Preservation infrastructure and open access to digitised collections.',
    amount: { value: 3500000, currency: 'USD' },
    year: '2023',
    topics: ['open access', 'heritage', 'public goods', 'open source'],
    countries: ['US'],
    projectUrl: 'https://archive.org/',
    source: 'irs-990',
  },
  {
    sourceId: 'grantmakers-io',
    funder: { name: 'Arcadia Fund', id: 'arcadia-fund' },
    recipient: 'Endangered Archives Programme — British Library',
    purpose: 'Digitisation of at-risk archival material in the Global South.',
    amount: { value: 2800000, currency: 'GBP' },
    year: '2022',
    topics: ['heritage', 'open access', 'research'],
    countries: ['GB'],
    source: 'irs-990',
  },
  {
    sourceId: 'ethereum-esp',
    funder: { name: 'Ethereum Foundation', id: 'ethereum-foundation' },
    recipient: 'Circom & snarkjs',
    purpose: 'Zero-knowledge circuit compiler and proving toolchain maintenance.',
    amount: { value: 320000, currency: 'USD' },
    year: '2024',
    topics: ['cryptography', 'open source', 'privacy', 'crypto'],
    countries: ['ES'],
    source: 'funder-report',
  },
  {
    sourceId: 'ethereum-esp',
    funder: { name: 'Ethereum Foundation', id: 'ethereum-foundation' },
    recipient: 'Reth / Ethereum client diversity',
    purpose: 'Independent execution client development to reduce single-client consensus risk.',
    amount: { value: 550000, currency: 'USD' },
    year: '2023',
    topics: ['crypto', 'open source', 'infrastructure', 'security'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'wellcome',
    funder: { name: 'Wellcome Trust', id: 'wellcome-trust' },
    recipient: 'Open Research Fund — reproducibility infrastructure',
    purpose: 'Tooling for reproducible computational research and open publication of negative results.',
    amount: { value: 850000, currency: 'GBP' },
    year: '2023',
    topics: ['research', 'open access', 'health', 'open source'],
    countries: ['GB'],
    source: 'funder-report',
  },
  {
    sourceId: 'linux-foundation',
    funder: { name: 'Linux Foundation', id: 'linux-foundation' },
    recipient: 'OpenSSF Alpha-Omega — Python Software Foundation',
    purpose: 'Fund a dedicated security developer-in-residence for the Python ecosystem.',
    amount: { value: 400000, currency: 'USD' },
    year: '2024',
    topics: ['security', 'open source', 'infrastructure'],
    countries: ['US'],
    source: 'press-release',
  },
  {
    sourceId: 'linux-foundation',
    funder: { name: 'Linux Foundation', id: 'linux-foundation' },
    recipient: 'OpenSSF Alpha-Omega — Rust Foundation',
    purpose: 'Security engineering capacity for crates.io and the Rust toolchain supply chain.',
    amount: { value: 460000, currency: 'USD' },
    year: '2023',
    topics: ['security', 'open source', 'developer tools'],
    countries: ['US'],
    source: 'press-release',
  },
  {
    sourceId: 'ukri',
    funder: { name: 'UK Research and Innovation', id: 'ukri' },
    recipient: 'Alan Turing Institute — AI safety programme',
    purpose: 'National capacity building for AI evaluation and assurance research.',
    amount: { value: 4200000, currency: 'GBP' },
    year: '2024',
    topics: ['ai safety', 'ai', 'research', 'policy'],
    countries: ['GB'],
    source: 'funder-report',
  },
  {
    sourceId: 'eu-horizon',
    funder: { name: 'European Commission', id: 'european-commission' },
    recipient: 'NGI Zero consortium (via NLnet)',
    purpose: 'Umbrella funding enabling hundreds of small open source grants across Europe.',
    amount: { value: 24000000, currency: 'EUR' },
    year: '2023',
    topics: ['open source', 'internet', 'privacy', 'public goods'],
    countries: ['NL', 'GLOBAL'],
    source: 'funder-report',
  },
  {
    sourceId: 'eu-horizon',
    funder: { name: 'European Commission', id: 'european-commission' },
    recipient: 'EuroHPC — open scientific computing access',
    purpose: 'Open access compute allocations for European researchers including AI workloads.',
    amount: { value: 15000000, currency: 'EUR' },
    year: '2024',
    topics: ['research', 'ai', 'infrastructure', 'science'],
    countries: ['GLOBAL'],
    source: 'funder-report',
  },
];
