import type { FundingType, OpportunityStatus } from '../types';

/**
 * Bundled snapshot of the index.
 *
 * OpenGrantIndex is a *view over Nostr*: the live corpus is whatever kind 35231
 * events the configured relays return. This bundled snapshot exists so the site
 * is useful on first paint, before any relay has answered, and so the project is
 * demonstrably functional without a running crawl fleet.
 *
 * Deadlines are expressed as day offsets from load time rather than absolute
 * dates so the snapshot never rots into a wall of expired listings.
 */
export interface SeedOpportunity {
  sourceId: string;
  title: string;
  summary: string;
  description: string;
  url: string;
  applyUrl?: string;
  fundingType: FundingType;
  status: OpportunityStatus;
  /** Days from now; negative means already closed. */
  deadlineInDays?: number;
  opensInDays?: number;
  amount?: { min?: number; max?: number; currency: string };
  topics: string[];
  countries: string[];
  remote?: boolean;
  eligibility: string;
  funder: { name: string; id: string };
  /** Days since the crawler last verified the page. */
  checkedDaysAgo: number;
  extraction?: { pipeline: string; model?: string; confidence?: number };
}

export const SEED_OPPORTUNITIES: SeedOpportunity[] = [
  {
    sourceId: 'nlnet',
    title: 'NGI Zero Commons Fund',
    summary: 'Grants of €5,000–€50,000 for free and open source technology that reclaims the public nature of the internet.',
    description:
      'The NGI Zero Commons Fund is a broad fund supporting people and organisations that contribute to the open internet as a commons. It funds work on free and open source software, open hardware, open standards and open data — from cryptographic protocols to accessibility tooling to search infrastructure.\n\nApplications are reviewed in bi-monthly cycles. There is no minimum organisational size: individual contributors are explicitly welcome, and NLnet handles the administrative overhead so that small teams are not disadvantaged. Successful applicants receive a grant agreement covering agreed deliverables, plus free access to security audits, accessibility review, licence compliance checks and translation support.',
    url: 'https://nlnet.nl/commonsfund/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 38,
    amount: { min: 5000, max: 50000, currency: 'EUR' },
    topics: ['open source', 'privacy', 'internet', 'security', 'public goods'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Individuals, informal teams, non-profits and SMEs anywhere in the world. Work must be published under a free/open licence. Preference for projects with an EU nexus, but non-EU applicants are regularly funded.',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    checkedDaysAgo: 1,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.96 },
  },
  {
    sourceId: 'nlnet',
    title: 'NGI Zero Core Fund',
    summary: 'Funding for foundational internet technology: protocols, routing, identity, transport and trust infrastructure.',
    description:
      'NGI Zero Core targets the deep plumbing of the internet — the layers most users never see and almost no one funds. Typical grantees work on DNS privacy, routing security, decentralised identity, peer-to-peer transport, and reproducible builds.\n\nProjects are expected to produce working code and, where relevant, contribute back to standards bodies. Grants are milestone-based, and NLnet provides in-kind support for security review and standardisation.',
    url: 'https://nlnet.nl/core/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 38,
    amount: { min: 5000, max: 50000, currency: 'EUR' },
    topics: ['open source', 'internet', 'security', 'cryptography', 'infrastructure'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Open to individuals and organisations globally. Must target core internet technology and release under a free/open licence.',
    funder: { name: 'NLnet Foundation', id: 'nlnet-foundation' },
    checkedDaysAgo: 1,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.95 },
  },
  {
    sourceId: 'sovereign-tech',
    title: 'Sovereign Tech Fund — Investment Programme',
    summary: 'Direct investment in maintenance, security and resilience of critical open source infrastructure.',
    description:
      'The Sovereign Tech Fund pays for the work that keeps critical open source alive: dependency modernisation, test coverage, CI/CD, documentation, security hardening and long-overdue refactors. It is explicitly not an innovation fund.\n\nEngagement usually begins with a scoping conversation rather than a form. Maintainers are contracted directly, and payments are tied to a work plan negotiated with the maintainer, not imposed by the funder. Applications are accepted on a rolling basis.',
    url: 'https://www.sovereign.tech/programs/fund',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 50000, max: 300000, currency: 'EUR' },
    topics: ['open source', 'infrastructure', 'security', 'maintenance', 'public goods'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Maintainers of open source components with demonstrable downstream dependency across critical infrastructure. Individual maintainers and companies both eligible; project must be under an OSI-approved licence.',
    funder: { name: 'Sovereign Tech Agency', id: 'sovereign-tech-agency' },
    checkedDaysAgo: 3,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.92 },
  },
  {
    sourceId: 'sovereign-tech',
    title: 'Sovereign Tech Fellowship for Maintainers',
    summary: 'Paid fellowship allowing maintainers of critical open source to work on their project as their job.',
    description:
      'The fellowship funds maintainers directly for their stewardship work — triage, review, release management, community care — rather than for shipping features. Fellows receive a stipend for a defined term and join a cohort with peer support.\n\nThe programme exists because burnout, not lack of ideas, is the primary failure mode of critical infrastructure maintenance.',
    url: 'https://www.sovereign.tech/programs/fellowship',
    fundingType: 'fellowship',
    status: 'upcoming',
    opensInDays: 24,
    deadlineInDays: 82,
    amount: { min: 20000, max: 60000, currency: 'EUR' },
    topics: ['open source', 'maintenance', 'infrastructure'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Active maintainers of widely-depended-upon open source projects. Must be able to invoice as an individual or through an entity.',
    funder: { name: 'Sovereign Tech Agency', id: 'sovereign-tech-agency' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'open-philanthropy',
    title: 'Request for Proposals: Technical AI Safety Research',
    summary: 'Multi-million-dollar RFP across 21 research areas in adversarial robustness, interpretability and model evaluation.',
    description:
      'Open Philanthropy is soliciting proposals across a broad set of technical AI safety research directions, including mechanistic interpretability, scalable oversight, adversarial robustness, dangerous-capability evaluations, and the science of deep learning.\n\nProposals are accepted from academic labs, independent researchers and non-profits. There are two stages: a short expression of interest, followed by an invited full proposal. Funding can cover salary, compute, and research engineer time. Compute-heavy proposals are explicitly welcome.',
    url: 'https://www.openphilanthropy.org/request-for-proposals-for-technical-ai-safety-research/',
    fundingType: 'rfp',
    status: 'open',
    deadlineInDays: 21,
    amount: { min: 100000, max: 5000000, currency: 'USD' },
    topics: ['ai safety', 'ai', 'research', 'machine learning'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Academic researchers, independent researchers, and non-profit research organisations worldwide. No citizenship restriction. Institutional overhead is negotiable.',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    checkedDaysAgo: 1,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.94 },
  },
  {
    sourceId: 'open-philanthropy',
    title: 'Abundance and Growth Fund',
    summary: 'Funding to accelerate economic growth and lower the cost of housing, energy and healthcare.',
    description:
      'A large new fund supporting policy research, advocacy and field-building aimed at removing barriers to abundance — permitting reform, energy deployment, immigration of skilled workers, and scientific metascience.\n\nGrants range from small research contracts to multi-year organisational support. Proposals are reviewed on a rolling basis with no fixed deadline.',
    url: 'https://www.openphilanthropy.org/abundance-and-growth/',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 50000, max: 2000000, currency: 'USD' },
    topics: ['economics', 'policy', 'research', 'climate', 'housing'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Non-profits, think tanks, academic institutions and fiscally-sponsored projects.',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    checkedDaysAgo: 6,
  },
  {
    sourceId: 'opensats',
    title: 'OpenSats General Fund — Bitcoin FOSS',
    summary: 'Rolling grants for contributors to Bitcoin and Lightning free and open source software.',
    description:
      'The General Fund supports developers, designers, researchers, educators and translators working on Bitcoin free and open source software. Grants are typically 3–12 months of funded work and are renewable.\n\nApplications are reviewed continuously by a rotating committee. There is no deadline and no organisational requirement — the majority of grantees are individuals. Work must be publicly licensed and publicly developed.',
    url: 'https://opensats.org/apply',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 10000, max: 100000, currency: 'USD' },
    topics: ['bitcoin', 'open source', 'privacy', 'cryptography'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Individuals and teams anywhere. Project must be free and open source. Anonymous and pseudonymous applicants are accepted.',
    funder: { name: 'OpenSats', id: 'opensats' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'opensats',
    title: 'OpenSats Nostr Fund',
    summary: 'Dedicated funding for Nostr clients, relays, libraries and protocol work.',
    description:
      'The Nostr Fund supports the protocol ecosystem directly: relay implementations, client development, NIP authorship, libraries, key management, and Nostr-native infrastructure such as media hosting and zap plumbing.\n\nGrants are announced publicly, and increasingly published as Nostr events by OpenSats itself — which is exactly the pattern this index is designed to consume: the funder is the primary source, no crawling required.',
    url: 'https://opensats.org/funds/nostr',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 5000, max: 75000, currency: 'USD' },
    topics: ['nostr', 'open source', 'privacy', 'decentralization'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Anyone building on Nostr. Pseudonymous applicants welcome. Must ship publicly.',
    funder: { name: 'OpenSats', id: 'opensats' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'ethereum-esp',
    title: 'Ethereum Foundation Ecosystem Support — Small Grants',
    summary: 'Grants up to $30,000 for early-stage Ethereum public goods, tooling and research.',
    description:
      'Small Grants fund experiments, community efforts, documentation, developer tooling and early research relevant to the Ethereum ecosystem. Decisions typically come within a few weeks.\n\nThe programme is deliberately low-friction: a short form, no pitch deck, no equity, no token. Larger or longer projects are routed to the general ESP inquiry process instead.',
    url: 'https://esp.ethereum.foundation/small-grants',
    fundingType: 'grant',
    status: 'rolling',
    amount: { max: 30000, currency: 'USD' },
    topics: ['crypto', 'open source', 'cryptography', 'research', 'education'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Individuals and teams globally. Output must be open source and non-commercial, or provide clear public-good value.',
    funder: { name: 'Ethereum Foundation', id: 'ethereum-foundation' },
    checkedDaysAgo: 4,
  },
  {
    sourceId: 'ethereum-esp',
    title: 'Academic Grants Round — Ethereum Research',
    summary: 'Annual round funding academic research on cryptography, consensus, privacy and mechanism design.',
    description:
      'The academic round funds university-affiliated research relevant to Ethereum: consensus protocols, zero-knowledge cryptography, formal verification, privacy-preserving systems, and cryptoeconomic mechanism design.\n\nAwards can cover PhD stipends, postdoctoral positions, conference travel and compute. Proposals are evaluated by a panel of external academics alongside Foundation researchers.',
    url: 'https://esp.ethereum.foundation/academic-grants',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 12,
    amount: { min: 25000, max: 250000, currency: 'USD' },
    topics: ['crypto', 'cryptography', 'research', 'privacy', 'formal verification'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Researchers affiliated with an academic institution. PhD students may apply with a faculty sponsor. Global.',
    funder: { name: 'Ethereum Foundation', id: 'ethereum-foundation' },
    checkedDaysAgo: 1,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.89 },
  },
  {
    sourceId: 'gitcoin',
    title: 'GG Web3 Infrastructure Matching Round',
    summary: 'Quadratic-funding matching pool for open source web3 infrastructure and developer tooling.',
    description:
      'A community matching round in which many small donations determine how a shared matching pool is allocated. Projects apply to be listed; donors decide the distribution; quadratic matching amplifies breadth of support over size of cheque.\n\nRounds are short — usually two weeks of active donation — so listing deadlines matter far more than in traditional grantmaking. This index recrawls Gitcoin hourly for exactly this reason.',
    url: 'https://grants.gitcoin.co/',
    fundingType: 'matching',
    status: 'open',
    deadlineInDays: 8,
    amount: { min: 500, max: 60000, currency: 'USD' },
    topics: ['crypto', 'public goods', 'open source', 'developer tools'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Open source projects with a public repository and a verifiable maintainer. Must pass Gitcoin sybil review.',
    funder: { name: 'Gitcoin', id: 'gitcoin' },
    checkedDaysAgo: 0,
  },
  {
    sourceId: 'mozilla',
    title: 'Mozilla Technology Fund — Open Source AI Auditing Tools',
    summary: 'Awards for open source tools that audit, evaluate or expose bias in AI systems.',
    description:
      'The Mozilla Technology Fund supports open source projects that make AI systems more accountable: dataset auditing tools, bias measurement frameworks, model documentation tooling, and infrastructure for independent researcher access.\n\nAwardees receive funding plus structured mentorship on governance, security and community building. Projects must already have working code — this is not a fund for ideas.',
    url: 'https://foundation.mozilla.org/en/what-we-fund/awards/mozilla-technology-fund/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 45,
    amount: { min: 25000, max: 75000, currency: 'USD' },
    topics: ['ai', 'open source', 'privacy', 'accountability', 'research'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Existing open source projects with a public repository under an OSI licence. Individuals, collectives and non-profits worldwide.',
    funder: { name: 'Mozilla Foundation', id: 'mozilla-foundation' },
    checkedDaysAgo: 3,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.91 },
  },
  {
    sourceId: 'mozilla',
    title: 'Mozilla Senior Fellowship in Trustworthy AI',
    summary: '12-month paid fellowship for researchers, engineers and activists working on AI accountability.',
    description:
      'Senior Fellows spend a year working on a self-directed project advancing trustworthy AI, embedded in Mozilla\'s network of researchers, policy people and technologists. The fellowship covers a competitive stipend, benefits, travel and a project budget.\n\nPast fellows have produced investigative research, open datasets, policy frameworks and widely-used auditing tools.',
    url: 'https://foundation.mozilla.org/en/what-we-fund/fellowships/',
    fundingType: 'fellowship',
    status: 'open',
    deadlineInDays: 31,
    amount: { min: 75000, max: 100000, currency: 'USD' },
    topics: ['ai', 'privacy', 'human rights', 'policy', 'research'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Mid-career or senior practitioners. No degree requirement. Must be able to work legally in a country where Mozilla can contract.',
    funder: { name: 'Mozilla Foundation', id: 'mozilla-foundation' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'nsf',
    title: 'Safe Learning-Enabled Systems (SLES)',
    summary: 'NSF programme funding foundational research on provable safety guarantees for AI systems.',
    description:
      'SLES supports research toward learning-enabled systems that are safe by design: formal specification of safety properties, verification of learned components, robustness under distribution shift, and runtime monitoring.\n\nProposals must include a concrete safety property and a plan to establish it with evidence. Collaboration between machine learning and formal methods researchers is strongly encouraged. Standard NSF eligibility and cost-sharing rules apply.',
    url: 'https://www.nsf.gov/funding/opportunities/sles-safe-learning-enabled-systems',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 67,
    amount: { min: 250000, max: 1500000, currency: 'USD' },
    topics: ['ai safety', 'ai', 'research', 'formal verification', 'science'],
    countries: ['US'],
    remote: false,
    eligibility:
      'US institutions of higher education and non-profit research organisations. PI must be affiliated with an eligible US institution. International collaborators may participate without NSF funding.',
    funder: { name: 'US National Science Foundation', id: 'nsf' },
    checkedDaysAgo: 5,
    extraction: { pipeline: 'ogi-extract/1', model: 'pdf+llm', confidence: 0.86 },
  },
  {
    sourceId: 'nsf',
    title: 'Pathways to Enable Open-Source Ecosystems (POSE)',
    summary: 'Funding to build sustainable governance and community infrastructure around open source research software.',
    description:
      'POSE does not fund the writing of new software. It funds the scaffolding that lets existing open source research products survive: governance structures, contributor onboarding, security practices, CI infrastructure and community management.\n\nPhase I awards are planning grants; Phase II awards fund the actual ecosystem build-out over three years. This is one of the very few government programmes that treats open source sustainability as a first-class research infrastructure problem.',
    url: 'https://www.nsf.gov/funding/opportunities/pose-pathways-enable-open-source-ecosystems',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 54,
    amount: { min: 300000, max: 1500000, currency: 'USD' },
    topics: ['open source', 'research', 'infrastructure', 'science', 'education'],
    countries: ['US'],
    remote: false,
    eligibility:
      'US universities, non-profits and, for some tracks, small businesses. Requires an existing open source product with demonstrated adoption.',
    funder: { name: 'US National Science Foundation', id: 'nsf' },
    checkedDaysAgo: 4,
    extraction: { pipeline: 'ogi-extract/1', model: 'pdf+llm', confidence: 0.88 },
  },
  {
    sourceId: 'eu-horizon',
    title: 'Horizon Europe — Trustworthy AI and Human Oversight',
    summary: 'Collaborative EU research call on transparency, oversight and robustness of AI systems.',
    description:
      'A Research and Innovation Action under Cluster 4 (Digital, Industry and Space) funding consortium research on human oversight of AI systems, explainability in high-stakes deployment, and technical means of complying with the AI Act.\n\nProposals require a consortium of at least three independent legal entities from three different EU Member States or Associated Countries. Typical project size is €4–6 million over 36 months, split across partners.',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',
    fundingType: 'rfp',
    status: 'open',
    deadlineInDays: 74,
    amount: { min: 3000000, max: 6000000, currency: 'EUR' },
    topics: ['ai', 'research', 'policy', 'digital', 'accountability'],
    countries: ['AT', 'BE', 'DE', 'DK', 'ES', 'FI', 'FR', 'IE', 'IT', 'NL', 'PL', 'PT', 'SE'],
    remote: false,
    eligibility:
      'Consortium of ≥3 independent legal entities from ≥3 different EU Member States or Horizon Associated Countries. Universities, research organisations, SMEs and NGOs all eligible.',
    funder: { name: 'European Commission', id: 'european-commission' },
    checkedDaysAgo: 2,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.93 },
  },
  {
    sourceId: 'eu-horizon',
    title: 'Digital Europe — Cybersecurity for Open Source Supply Chains',
    summary: 'Co-funded actions hardening the open source software supply chain across the EU.',
    description:
      'A Digital Europe Programme call supporting deployment-oriented work on software bill of materials tooling, reproducible builds, vulnerability coordination and CRA compliance for open source stewards.\n\nUnlike Horizon research actions, Digital Europe funds capability deployment at 50% co-funding for most participants, with higher rates for SMEs and non-profits.',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/programmes/digital',
    fundingType: 'rfp',
    status: 'open',
    deadlineInDays: 29,
    amount: { min: 1000000, max: 4000000, currency: 'EUR' },
    topics: ['security', 'open source', 'infrastructure', 'digital'],
    countries: ['AT', 'BE', 'BG', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HU', 'IE', 'IT', 'LT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK'],
    remote: false,
    eligibility:
      'Legal entities established in EU Member States or Digital Europe Associated Countries. Consortium required for most topics.',
    funder: { name: 'European Commission', id: 'european-commission' },
    checkedDaysAgo: 3,
  },
  {
    sourceId: 'prototype-fund',
    title: 'Prototype Fund Round — Public Interest Software',
    summary: 'Up to €95,000 over six months for individuals and small teams building open source public-interest tools.',
    description:
      'The Prototype Fund lets developers, designers and researchers spend six months building a public-interest software prototype without needing a company, an institution or a business model.\n\nEverything funded must be released under an open licence. Rounds open twice a year, and the application is deliberately short — a few pages, in German or English. Roughly one in six applications is funded.',
    url: 'https://prototypefund.de/en/apply/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 17,
    amount: { max: 95000, currency: 'EUR' },
    topics: ['open source', 'civic tech', 'privacy', 'education', 'public goods'],
    countries: ['DE'],
    remote: true,
    eligibility:
      'Individuals or teams of up to four resident in Germany. No company required — in fact solo developers are the typical grantee. Output must be open source.',
    funder: { name: 'Prototype Fund', id: 'prototype-fund' },
    checkedDaysAgo: 1,
    extraction: { pipeline: 'ogi-extract/1', model: 'rules+llm', confidence: 0.9 },
  },
  {
    sourceId: 'linux-foundation',
    title: 'LFX Mentorship — Spring Term',
    summary: 'Paid 12-week mentorship working on a Linux Foundation project with an experienced maintainer.',
    description:
      'LFX Mentorship pays newcomers a stipend to work on a real open source project — Kubernetes, Node.js, OpenSSF, Hyperledger and dozens of others — supervised by an existing maintainer.\n\nStipends vary by region. Three terms run each year, and competition per project is high, so applying to a project where you have already made a small contribution dramatically improves your odds.',
    url: 'https://lfx.linuxfoundation.org/tools/mentorship/',
    fundingType: 'fellowship',
    status: 'open',
    deadlineInDays: 9,
    amount: { min: 3000, max: 6600, currency: 'USD' },
    topics: ['open source', 'education', 'security', 'developer tools'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Anyone 18+, including students and career changers. Some projects prioritise first-time contributors. Regional stipend tiers apply.',
    funder: { name: 'Linux Foundation', id: 'linux-foundation' },
    checkedDaysAgo: 1,
  },
  {
    sourceId: 'linux-foundation',
    title: 'OpenSSF Alpha-Omega Security Funding',
    summary: 'Direct funding for security improvements in the most critical open source projects.',
    description:
      'Alpha-Omega funds two tracks: "Alpha" works hand-in-hand with the most critical projects on threat modelling and security engineering, while "Omega" applies automated analysis at scale across the long tail of ten thousand packages.\n\nEngagements are negotiated rather than granted — a security engineer or maintainer time is funded against an agreed plan.',
    url: 'https://alpha-omega.dev/',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 25000, max: 500000, currency: 'USD' },
    topics: ['security', 'open source', 'infrastructure'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Maintainers and foundations stewarding widely-used open source packages. Ecosystem-level proposals preferred over single-package fixes.',
    funder: { name: 'Linux Foundation', id: 'linux-foundation' },
    checkedDaysAgo: 7,
  },
  {
    sourceId: 'ukri',
    title: 'EPSRC Open Fellowships',
    summary: 'Long-duration UK fellowships giving researchers freedom to pursue ambitious engineering and physical sciences work.',
    description:
      'Open Fellowships fund a researcher rather than a project, for up to five years, with unusual latitude to change direction. Awards cover salary, research costs, and a team where justified.\n\nThe scheme is deliberately open to non-traditional career paths, including researchers returning after a career break and those moving from industry.',
    url: 'https://www.ukri.org/opportunity/epsrc-open-fellowships/',
    fundingType: 'fellowship',
    status: 'open',
    deadlineInDays: 41,
    amount: { min: 300000, max: 1500000, currency: 'GBP' },
    topics: ['research', 'science', 'engineering', 'ai'],
    countries: ['GB'],
    remote: false,
    eligibility:
      'Researchers based at, or with an offer from, an eligible UK research organisation. No fixed years-since-PhD limit. Part-time applications accepted.',
    funder: { name: 'UK Research and Innovation', id: 'ukri' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'wellcome',
    title: 'Wellcome Discovery Awards',
    summary: 'Up to eight years of funding for bold, curiosity-driven health research.',
    description:
      'Discovery Awards support researchers pursuing ambitious questions in any area relevant to human health — including basic biology, mental health, and the health effects of climate change.\n\nThe scheme funds teams as well as individuals, and explicitly asks applicants to describe research culture and team wellbeing as part of the proposal. Two-stage application with a preliminary form.',
    url: 'https://wellcome.org/grant-funding/schemes/discovery-awards',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 58,
    amount: { min: 500000, max: 4000000, currency: 'GBP' },
    topics: ['health', 'research', 'climate', 'mental health', 'biomedical'],
    countries: ['GLOBAL'],
    remote: false,
    eligibility:
      'Researchers at eligible organisations in the UK, Republic of Ireland, or low- and middle-income countries. Host organisation must administer the award.',
    funder: { name: 'Wellcome Trust', id: 'wellcome-trust' },
    checkedDaysAgo: 6,
  },
  {
    sourceId: 'wellcome',
    title: 'Climate Impacts Awards — Health and Wellbeing',
    summary: 'Research funding on how climate change affects mental and physical health, and what to do about it.',
    description:
      'This scheme funds interdisciplinary research on climate and health: heat and mental health, infectious disease range shifts, health system resilience, and the health co-benefits of mitigation.\n\nApplications from low- and middle-income country institutions are strongly encouraged, and equitable partnership between Global North and South collaborators is an assessment criterion rather than an afterthought.',
    url: 'https://wellcome.org/grant-funding/schemes/climate-impacts-awards',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 26,
    amount: { min: 250000, max: 3000000, currency: 'GBP' },
    topics: ['climate', 'health', 'research', 'global health'],
    countries: ['GLOBAL'],
    remote: false,
    eligibility:
      'Eligible research organisations worldwide, with a strong preference for consortia including LMIC-based leadership.',
    funder: { name: 'Wellcome Trust', id: 'wellcome-trust' },
    checkedDaysAgo: 4,
  },
  {
    sourceId: 'knight-foundation',
    title: 'Knight Local News Sustainability Fund',
    summary: 'Grants for local newsrooms building durable business and technology infrastructure.',
    description:
      'Supports local and community news organisations in the United States to build revenue diversification, audience technology, and shared back-office infrastructure. Collaborative applications from multiple newsrooms are prioritised.\n\nThe fund is explicitly interested in open source and shared tooling that reduces per-newsroom cost.',
    url: 'https://knightfoundation.org/programs/journalism/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 35,
    amount: { min: 50000, max: 500000, currency: 'USD' },
    topics: ['journalism', 'civic tech', 'education', 'open source'],
    countries: ['US'],
    remote: false,
    eligibility:
      'US-based 501(c)(3) news organisations, or for-profit newsrooms via a fiscal sponsor. Collaboratives encouraged.',
    funder: { name: 'John S. and James L. Knight Foundation', id: 'knight-foundation' },
    checkedDaysAgo: 5,
  },
  {
    sourceId: 'aisafety-funding',
    title: 'Long-Term Future Fund — Rolling Applications',
    summary: 'Fast, flexible grants for individuals working on AI safety, biosecurity and existential risk reduction.',
    description:
      'The LTFF funds individuals more than institutions: independent researchers, upskilling transitions, small research teams, and field-building projects. Decisions are often made within weeks, and small requests are reviewed fastest.\n\nBecause it funds people at career transitions, the LTFF is frequently the first money a new AI safety researcher receives.',
    url: 'https://funds.effectivealtruism.org/funds/far-future',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 5000, max: 200000, currency: 'USD' },
    topics: ['ai safety', 'research', 'biosecurity', 'forecasting'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Individuals and small teams worldwide. Self-funded upskilling, independent research, and organisation seed funding all in scope.',
    funder: { name: 'Manifund', id: 'manifund' },
    checkedDaysAgo: 3,
  },
  {
    sourceId: 'aisafety-funding',
    title: 'Manifund Regranting — AI Safety',
    summary: 'Independent regrantors with their own budgets fund early AI safety work in public.',
    description:
      'Manifund gives experienced people a regranting budget and publishes every decision, comment and amount. Applicants pitch publicly and can be funded by any regrantor whose thesis matches.\n\nThe radical transparency makes Manifund the cleanest available dataset of small, fast AI safety funding decisions — and a useful counterweight to the opacity of most philanthropy.',
    url: 'https://manifund.org/',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 1000, max: 100000, currency: 'USD' },
    topics: ['ai safety', 'research', 'forecasting'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Anyone. Projects are pitched publicly; regrantors choose independently.',
    funder: { name: 'Manifund', id: 'manifund' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'nostr-announcements',
    title: 'HRF Bitcoin Development Fund — Quarterly Round',
    summary: 'Bitcoin and privacy tooling grants for developers working under authoritarian regimes.',
    description:
      'The Human Rights Foundation\'s Bitcoin Development Fund makes quarterly grants to developers building privacy, censorship-resistance and financial-freedom tools, with priority for contributors living under authoritarian governments.\n\nGrants are paid in bitcoin. Pseudonymous applications are explicitly accepted, and HRF announces recipients publicly — increasingly on Nostr.',
    url: 'https://hrf.org/devfund/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 15,
    amount: { min: 5000, max: 100000, currency: 'USD' },
    topics: ['bitcoin', 'privacy', 'human rights', 'censorship resistance', 'nostr'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Developers, educators and researchers worldwide. Pseudonymous applicants welcome. Priority for those in authoritarian jurisdictions.',
    funder: { name: 'Human Rights Foundation', id: 'human-rights-foundation' },
    checkedDaysAgo: 1,
  },
  {
    sourceId: 'github-sponsors-orgs',
    title: 'Rust Foundation Community Grants',
    summary: 'Grants for maintainers, educators and event organisers in the Rust ecosystem.',
    description:
      'Discovered by the GitHub organisation crawler from a GRANTS.md file rather than from any foundation landing page — a good illustration of why a website-only crawler misses a large fraction of real funding.\n\nThe programme funds maintainer time, infrastructure work, documentation, and community events across the Rust ecosystem.',
    url: 'https://foundation.rust-lang.org/grants/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 48,
    amount: { min: 1000, max: 30000, currency: 'USD' },
    topics: ['open source', 'developer tools', 'education', 'security'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Rust community members worldwide. Individuals and small groups; no institutional affiliation needed.',
    funder: { name: 'Linux Foundation', id: 'linux-foundation' },
    checkedDaysAgo: 8,
    extraction: { pipeline: 'ogi-extract/1', model: 'github+llm', confidence: 0.72 },
  },
  {
    sourceId: 'arcadia-fund',
    title: 'Arcadia Open Access and Open Knowledge',
    summary: 'Large multi-year grants to make scholarly and cultural knowledge openly available.',
    description:
      'Arcadia funds infrastructure and institutions that push knowledge into the open: open access publishing infrastructure, digitisation of endangered archives, and open bibliographic data.\n\nGrants are made by invitation following an initial enquiry, and are typically large and multi-year. The index records this programme so that researchers can see the funder exists, even though there is no open application form.',
    url: 'https://www.arcadiafund.org.uk/grants',
    fundingType: 'grant',
    status: 'rolling',
    amount: { min: 250000, max: 5000000, currency: 'USD' },
    topics: ['open access', 'heritage', 'research', 'public goods'],
    countries: ['GLOBAL'],
    remote: false,
    eligibility:
      'Established institutions and non-profits. By invitation following an enquiry — no open application form.',
    funder: { name: 'Arcadia Fund', id: 'arcadia-fund' },
    checkedDaysAgo: 12,
  },
  {
    sourceId: 'ford-foundation',
    title: 'Digital Infrastructure Insights Fund',
    summary: 'Research grants studying the maintenance, funding and security of critical digital infrastructure.',
    description:
      'A collaborative fund from Ford Foundation, Sloan, Omidyar and Mozilla supporting research *about* open source rather than research *using* it: who maintains critical dependencies, how they are paid, how projects fail, and what interventions actually work.\n\nOutputs must be published openly. Both academic and practitioner-led research is funded.',
    url: 'https://www.fordfoundation.org/work/our-grants/',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 23,
    amount: { min: 20000, max: 200000, currency: 'USD' },
    topics: ['open source', 'research', 'infrastructure', 'public goods', 'policy'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Researchers, practitioners and non-profits worldwide. Independent researchers may apply through a fiscal host.',
    funder: { name: 'Ford Foundation', id: 'ford-foundation' },
    checkedDaysAgo: 4,
  },
  {
    sourceId: 'darpa',
    title: 'DARPA Artificial Intelligence Cyber Challenge — Follow-on BAA',
    summary: 'Broad Agency Announcement for automated vulnerability discovery and repair systems.',
    description:
      'A Broad Agency Announcement soliciting research on cyber reasoning systems that find and fix vulnerabilities in real code without human intervention. Distributed as a 60-page PDF with deadlines buried in prose — the exact case the PDF + OCR extraction plugin exists to handle.\n\nAwards range widely; abstracts are strongly encouraged before full proposals.',
    url: 'https://www.darpa.mil/work-with-us/opportunities',
    fundingType: 'rfp',
    status: 'open',
    deadlineInDays: 19,
    amount: { min: 500000, max: 10000000, currency: 'USD' },
    topics: ['security', 'ai', 'research', 'developer tools'],
    countries: ['US'],
    remote: false,
    eligibility:
      'US and eligible foreign entities; some tracks restricted to US persons. Universities, small businesses and primes all eligible.',
    funder: { name: 'US National Science Foundation', id: 'nsf' },
    checkedDaysAgo: 9,
    extraction: { pipeline: 'ogi-extract/1', model: 'pdf+ocr+llm', confidence: 0.64 },
  },
  {
    sourceId: 'grants-gov',
    title: 'NEH Digital Humanities Advancement Grants',
    summary: 'US federal funding for digital projects and tools across the humanities.',
    description:
      'Supports innovative digital humanities projects at three levels: early-stage experimentation, implementation of proven approaches, and scaling of successful tools. Open source deliverables are encouraged.\n\nDiscovered through the Grants.gov Search2 API, which is the single highest-volume structured source in the index.',
    url: 'https://www.grants.gov/search-results-detail/neh-dhag',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 62,
    amount: { min: 30000, max: 350000, currency: 'USD' },
    topics: ['education', 'heritage', 'research', 'open source', 'arts'],
    countries: ['US'],
    remote: false,
    eligibility:
      'US non-profits, institutions of higher education, and state/local governments. Individuals are not eligible.',
    funder: { name: 'US National Science Foundation', id: 'nsf' },
    checkedDaysAgo: 3,
  },
  {
    sourceId: 'nih',
    title: 'NIH Exploratory/Developmental Research Grant (R21)',
    summary: 'Two-year seed funding for high-risk, high-reward early-stage biomedical research.',
    description:
      'The R21 mechanism funds exploratory work where preliminary data is limited but the potential impact is high. Standard due dates recur three times per year, which makes this an ideal target for automatic deadline projection: the crawler predicts the next cycle rather than waiting for a new page.\n\nBudget is capped at $275,000 direct costs over two years, with no more than $200,000 in any single year.',
    url: 'https://grants.nih.gov/grants/guide/pa-files/PA-23-R21.html',
    fundingType: 'grant',
    status: 'open',
    deadlineInDays: 33,
    amount: { max: 275000, currency: 'USD' },
    topics: ['health', 'biomedical', 'research'],
    countries: ['US'],
    remote: false,
    eligibility:
      'US and, for some institutes, foreign institutions. PI must have an eRA Commons account through an eligible organisation.',
    funder: { name: 'US National Science Foundation', id: 'nsf' },
    checkedDaysAgo: 6,
    extraction: { pipeline: 'ogi-extract/1', model: 'pdf+llm', confidence: 0.81 },
  },
  {
    sourceId: 'community',
    title: 'Nostr Protocol Hackathon — Privacy Track',
    summary: 'Prize pool for the best privacy-preserving Nostr client or relay implementation.',
    description:
      'A community-submitted hackathon with a bitcoin prize pool for work on metadata-resistant messaging, private relays, and key management UX on Nostr.\n\nSubmitted by a community member rather than crawled, which is why this record carries a lower trust score until other participants attest to it.',
    url: 'https://nostr.build/hackathon-privacy-track',
    fundingType: 'hackathon',
    status: 'open',
    deadlineInDays: 27,
    amount: { min: 1000000, max: 21000000, currency: 'SATS' },
    topics: ['nostr', 'privacy', 'cryptography', 'open source'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Anyone. Teams of up to five. Submissions must be open source and working.',
    funder: { name: 'OpenSats', id: 'opensats' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'community',
    title: 'Open Data Journalism Micro-Bounties',
    summary: 'Small bounties for reproducible data journalism pipelines and public datasets.',
    description:
      'Community-submitted programme paying small bounties for cleaned, documented public datasets and reproducible analysis notebooks that other newsrooms can reuse.\n\nA good example of the long tail of funding that no institutional crawler would ever find.',
    url: 'https://datajournalism.example.org/bounties',
    fundingType: 'bounty',
    status: 'open',
    deadlineInDays: 11,
    amount: { min: 250, max: 2500, currency: 'USD' },
    topics: ['journalism', 'open data', 'civic tech'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Anyone. Payment on merged pull request.',
    funder: { name: 'John S. and James L. Knight Foundation', id: 'knight-foundation' },
    checkedDaysAgo: 14,
  },
  {
    sourceId: 'gitcoin',
    title: 'Climate Solutions Matching Round',
    summary: 'Quadratic funding round for open source climate measurement and mitigation tooling.',
    description:
      'Matching pool for projects working on emissions measurement, regenerative finance, energy data transparency and climate open data. Community donations determine allocation.',
    url: 'https://grants.gitcoin.co/climate-round',
    fundingType: 'matching',
    status: 'closed',
    deadlineInDays: -12,
    amount: { min: 500, max: 40000, currency: 'USD' },
    topics: ['climate', 'crypto', 'public goods', 'open data'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility: 'Open source climate projects with a public repository.',
    funder: { name: 'Gitcoin', id: 'gitcoin' },
    checkedDaysAgo: 2,
  },
  {
    sourceId: 'open-philanthropy',
    title: 'Career Development Fellowship — Biosecurity',
    summary: 'Funded transition support for people moving into biosecurity and pandemic preparedness work.',
    description:
      'Covers salary, tuition or self-study time for people building career capital in biosecurity — including public health, synthetic biology governance and biosurveillance.\n\nThe fellowship is designed for career changers, not for people already established in the field.',
    url: 'https://www.openphilanthropy.org/career-development-and-transition-funding/',
    fundingType: 'fellowship',
    status: 'open',
    deadlineInDays: 5,
    amount: { min: 30000, max: 150000, currency: 'USD' },
    topics: ['biosecurity', 'global health', 'research', 'education'],
    countries: ['GLOBAL'],
    remote: true,
    eligibility:
      'Individuals worldwide at a career transition point. No institutional affiliation required. Funding can cover degrees, self-study or unpaid research time.',
    funder: { name: 'Open Philanthropy', id: 'open-philanthropy' },
    checkedDaysAgo: 1,
  },
];
